name: build main 
on:
  push:
    branches-ignore:
      - "R/**"
      - "r/**"
      - "python/**"
      - "scala/**"
  pull_request:
    branches:
      - "**"
jobs:
  build:
    runs-on: larger
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        python: [ 3.12.3 ]
        python_minor: [ 3.12 ]
        numpy: [ 1.26.4 ]
        gdal: [ 3.10.1 ]
        spark: [ 3.5.2 ]
        R: [ 4.4.0 ]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build scala
        uses: ./.github/actions/scala_build
      - name: build python
        uses: ./.github/actions/python_build
      - name: build R
        uses: ./.github/actions/r_build
      - name: upload artefacts
        uses: ./.github/actions/upload_artefacts
