name: publish python package to pypi
on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build project and publish to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # Used to authenticate to PyPI via OIDC and sign the release's artifacts with sigstore-python.
      id-token: write
      # Used to attach signing artifacts to the published release.
      contents: write
    strategy:
      matrix:
        python: [ 3.12.3 ]
        numpy: [ 1.26.4 ]
        gdal: [ 3.10.2 ]
        spark: [ 3.5.2 ]
        R: [ 4.4.0 ]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build scala
        uses: ./.github/actions/scala_build
      - name: build python
        uses: ./.github/actions/python_build
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: python/dist/
